config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: :index
  resource :csv_upload, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :supplier
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/csv_uploads_controller.rb
class CsvUploadsController < ApplicationController
  def new
    @uploader = UploaderFormObject.new
  end

  def create
    uploader = UploaderFormObject.new(file: params.dig(:uploader_form_object, :file))
    uploader.save
    flash[:notice] = 'File successfully uploaded'
    redirect_to new_csv_upload_url
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.includes(:supplier).page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/csv_uploads/new.html.erb
<% if flash[:notice] %>
  <div><%= flash[:notice] %></div>
<% end %>

<h1>Upload CSV</h1>
<%= form_for @uploader, url: csv_upload_path, method: :post do |f| %>
    <%= f.file_field :file, accept: 'text/csv' %>
    <%= f.submit 'Upload' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Abmcloud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>
<h3><%= link_to 'Upload CSV', new_csv_upload_path %></h3>
<table>
  <thead>
  <th>SKU</th>
  <th>Код Постащика</th>
  <th>Доп. Поле 1</th>
  <th>Доп. Поле 2</th>
  <th>Доп. Поле 3</th>
  <th>Доп. Поле 4</th>
  <th>Доп. Поле 5</th>
  <th>Доп. Поле 6</th>
  <th>Цена</th>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.supplier.name %></td>
      <td><%= product.field1 %></td>
      <td><%= product.field2 %></td>
      <td><%= product.field3 %></td>
      <td><%= product.field4 %></td>
      <td><%= product.field5 %></td>
      <td><%= product.field6 %></td>
      <td><%= product.price %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @products %>